feat: Setup local user register & handle exception error to logger
Cophr/backend pull request #6
Opened 2023-03-23 19:33 UTC by a20688392

Setup local user register, handle exception error, and setup logger

Setup：
- local user register：setup user's entity, register api,and handle error
- handle exception error：setup handle error and return error response
- logger：record the error when hadle error as errors occur

2023-03-25 16:46 UTC, moontai0724 requested changes

2023-03-25 16:46 UTC, moontai0724 commented on src/core/all-exceptions.filter.ts
1. I think this should use `all-exception` instead of `all-exceptions`
2. I would recommend to organize this file in folder like `filters` or `exception-filter`

2023-03-25 16:46 UTC, moontai0724 commented on src/main.ts
> +  app.use(morgan("default", { stream: logStream }));
does not described in PR content, should consider to add description about this

2023-03-25 16:46 UTC, moontai0724 commented on src/main.ts
> +const logStream = fs.createWriteStream("api.log", {
does this mean to log into single file in root folder? I would recommend to reconsider about log file save path and segmentation policy like by size or by date etc...

2023-03-25 16:46 UTC, moontai0724 commented on src/core/models/http-exception-response.interface.ts
1. generaly we would use `model` to represent database models, to use this word here would be confusing.
2. I would recommend to reconsider how to organize these files, like use a `exception-filter` to organize `all-exceptions` and this type together.

2023-03-25 16:46 UTC, moontai0724 commented on src/core/all-exceptions.filter.ts
> +  };
why don't just use normal function declaration? seems like these content does not affected by execution domain.

2023-03-25 16:46 UTC, moontai0724 commented on src/core/all-exceptions.filter.ts
> +    fs.appendFile("error.log", errorLog, "utf8", err => {
1. recommend to make an independent logger service
2. recommend to reconsider about log file save path and segmentation policy like by size or by date etc...

2023-03-25 16:46 UTC, moontai0724 commented on src/core/all-exceptions.filter.ts
> +    }
would it be better to split these exceptions to independent filters?

2023-03-25 16:46 UTC, moontai0724 commented on src/users/entities/user.entity.ts
> +  name: string;
should not unique name property

2023-03-25 16:46 UTC, moontai0724 commented on src/database/migrations/1679539757893-UserInitMigration.ts
> +        \`password\` varchar(255) NOT NULL,
bcrypt hashed password should only need 60 char length

2023-03-25 16:46 UTC, moontai0724 commented on src/users/dto/create-user.dto.ts
> +  })
why limit password length? I would not limit this, or only limit minimum length

2023-03-25 16:46 UTC, moontai0724 commented on src/users/dto/create-user.dto.ts
> +  public readonly confirm: string;
I think backend can ignore password confirm field, this can be done by frontend

2023-03-25 16:46 UTC, moontai0724 commented on src/users/dto/create-user.dto.ts
> +  public readonly account: string;
may need a length limit and character limit like only accept numbers, alphabets and underscores.

2023-03-25 16:46 UTC, moontai0724 commented on src/users/dto/create-user.dto.ts
> +    description: "User showname",
use `User display name` may better

2023-03-25 16:46 UTC, moontai0724 commented on src/users/dto/create-user.dto.ts
> +  @IsEmail({}, { message: "email must be in mailbox format." })
use `email format does not correct` just fine

2023-03-25 16:46 UTC, moontai0724 commented on src/users/dto/create-user.dto.ts
`xxxx is required field` can use `xxxx is required` instead.

2023-03-25 16:46 UTC, moontai0724 commented on src/users/users.controller.spec.ts
> +describe("UsersController", () => {
it's a good chance to practice about unit test! recommend to write unit test about this!

2023-03-25 16:46 UTC, moontai0724 commented on src/users/users.controller.ts
> +    description: "Data Duplication",
seems like description does not match content?

2023-03-25 16:46 UTC, moontai0724 commented on src/users/users.service.ts
> +    return { statusCode: 201, message: data.name + " created successfully." };
IMO, can use one of following description:
1. created
2. successfully created
3. create succeed

2023-03-25 16:46 UTC, moontai0724 commented on src/users/users.service.ts
> +  async create(userDto: CreateUserParam): Promise<object> {
recommend to keep a blank line between functions

2023-03-25 16:46 UTC, moontai0724 commented on src/users/users.utils.ts
> +  errorHttpStatusCode: HttpStatus.UNPROCESSABLE_ENTITY,
generally will use 401 instead of 422 to represent that user given data is not correct.

2023-03-25 16:46 UTC, moontai0724 commented on src/users/users.utils.ts
should be able to migrate into user dto by [custom validator](https://github.com/typestack/class-validator#custom-validation-classes) and applied into property by `@Validate` decorator

2023-03-25 16:46 UTC, moontai0724 commented on src/users/users.controller.ts
> +  @ApiUnprocessableEntityResponse({
generally will use 401 instead of 422 to represent that user given data is not correct.

2023-03-25 16:46 UTC, moontai0724 commented on src/users/entities/user.entity.ts
> +  updateAt: Date;
may not need this property?

2023-03-25 16:46 UTC, moontai0724 commented on src/users/dto/create-user.dto.ts
> +    example: "showname",
it would be better to use a name or something

2023-03-25 16:46 UTC, moontai0724 commented on src/users/exceptions/create-conflict-error.exception.ts
> +    example: "email has been registered.",
should be an array of message

2023-03-25 16:46 UTC, moontai0724 commented on src/users/users.controller.ts
I recommend to create an auth module to handle `register`, `login` related features.

ref:
1. https://docs.nestjs.com/security/authentication
2. https://github.com/moontai0724/knowledge-king-back-end/blob/development/src/auth/auth.controller.ts

2023-04-02 14:04 UTC, a20688392 commented on src/core/all-exceptions.filter.ts
I change in commit https://github.com/Cophr/backend/pull/6/commits/874d07ca194c33cd95f7657309f15c952f915d05

2023-04-16 10:22 UTC, a20688392 commented on src/main.ts
> +  app.use(morgan("default", { stream: logStream }));
I change in commit 
https://github.com/Cophr/backend/pull/6/commits/42d00404893e53b88431790e8ff1283181003511
https://github.com/Cophr/backend/pull/6/commits/c19d7d34dc011a81104ef0e7c4c840131685e297

2023-04-16 10:22 UTC, a20688392 commented on src/main.ts
> +const logStream = fs.createWriteStream("api.log", {
I change in commit 
https://github.com/Cophr/backend/pull/6/commits/42d00404893e53b88431790e8ff1283181003511
https://github.com/Cophr/backend/pull/6/commits/c19d7d34dc011a81104ef0e7c4c840131685e297

2023-04-16 10:54 UTC, a20688392 commented on src/users/entities/user.entity.ts
> +  updateAt: Date;
I change in commit
https://github.com/Cophr/backend/pull/6/commits/0f4a61dd1baefbb14416ebdc180b4f0614ea9039

2023-04-16 10:55 UTC, a20688392 commented on src/users/entities/user.entity.ts
> +  name: string;
I change in commit
https://github.com/Cophr/backend/pull/6/commits/0f4a61dd1baefbb14416ebdc180b4f0614ea9039

2023-04-16 10:55 UTC, a20688392 commented on src/database/migrations/1679539757893-UserInitMigration.ts
> +        \`password\` varchar(255) NOT NULL,
I change in commit
https://github.com/Cophr/backend/pull/6/commits/0f4a61dd1baefbb14416ebdc180b4f0614ea9039

2023-04-16 15:44 UTC, moontai0724 commented on src/database/migrations/1679539757893-UserInitMigration.ts
> +        \`password\` varchar(255) NOT NULL,
Maybe able to directly modify the migration? idk if this work or not.

2023-06-08 14:47 UTC, closed without merging