Feature/local register
Cophr/backend pull request #7
Opened 2023-06-04 15:11 UTC by a20688392

本地使用者註冊和單元測試
- 本地使用者註冊：
  - 初始化資料庫表、註冊API、驗證資料格式
  - 單元測試
    - auth controller
      - 驗證資料格式和回應訊息
    - auth service
      - 驗證資料衝突和回應訊息
- 新增 dataSourceJest 是因為單元測試吃的是 TS
  - [feat: auth service unit test](https://github.com/Cophr/backend/commit/66b261e0961c6d468e8f96d7f5c2c2e7d0fffa5b)
- package.json 修改 jest參數
  - 會顯示全部詳細測試資訊
    - ```"test": "jest --verbose",```
  - 為了讓他能在 jest 單元測試抓到路徑，原本只能抓相對路徑
  - 範例：```src/users/entities/user.entity```
```
"moduleNameMapper": {
      "src/(.*)$": "<rootDir>/$1"
}
```

2023-06-06 11:46 UTC, moontai0724 commented on package.json
> +    "sqlite3": "^5.1.6",
may able to make it as dev dependency?

2023-06-06 12:24 UTC, moontai0724 commented on src/auth/auth.service.spec.ts
> +    });
`afterEach` 會在「每個 (each)」測試案例「執行後 (after)」跑，一整個 sub collection 只要執行一次就好

2023-06-06 12:24 UTC, moontai0724 commented on src/auth/auth.service.spec.ts
> +    });
`afterEach` 會在「每個 (each)」測試案例「執行後 (after)」跑，一整個 sub collection 只要執行一次就好

2023-06-06 12:24 UTC, moontai0724 commented on src/auth/auth.service.spec.ts
> +    });
`afterEach` 會在「每個 (each)」測試案例「執行後 (after)」跑，一整個 sub collection 只要執行一次就好

2023-06-06 12:24 UTC, moontai0724 commented on src/auth/auth.service.spec.ts
> +    });
建議可以把 `afterEach` 這種非測試案例與測試案例 `it(...)` 分開放，例如放到最前面或最後面。

2023-06-06 12:25 UTC, moontai0724 commented on src/auth/auth.service.spec.ts
> +      expect(errors.length).toBe(0);
不應在測試內做非測試方法的事情

2023-06-06 12:31 UTC, moontai0724 commented on src/auth/auth.controller.spec.ts
> +  });
controller 的 test 應該是要測試 controller 的方法是否如預期，這部分的測試應該要改成測試 controller 中的 function 是否會正確驗證傳入的 payload，而非直接拿 dto 來做驗證。

2023-06-06 12:45 UTC, moontai0724 commented on src/auth/auth.controller.spec.ts
> +    it("應該會發生資料驗證失敗，並返回 406 狀態碼", async () => {
`400` 才對

2023-06-06 12:46 UTC, moontai0724 commented on src/auth/auth.controller.spec.ts
> +    });
建議可以把 `afterEach` 這種非測試案例與測試案例 `it(...)` 分開放，例如放到最前面或最後面。

2023-06-06 12:47 UTC, moontai0724 commented on src/auth/auth.controller.spec.ts
> +    });
`afterEach` 會在「每個 (each)」測試案例「執行後 (after)」跑，一整個 sub collection 只要執行一次就好

2023-06-06 12:47 UTC, moontai0724 commented on src/auth/auth.controller.spec.ts
> +    });
`afterEach` 會在「每個 (each)」測試案例「執行後 (after)」跑，一整個 sub collection 只要執行一次就好

2023-06-06 13:23 UTC, moontai0724 commented on src/auth/auth.service.ts
> +    }
雖然這邊是我寫的 code 但我現在總感覺這個 try catch 跟 if 是多餘的w

2023-06-06 13:26 UTC, moontai0724 commented on src/users/dto/create-user.dto.ts
> +    description: "登入用帳號名",
老實說我希望登入用 email XD

2023-06-06 13:29 UTC, moontai0724 commented on src/users/entities/user.entity.ts
> +  createAt: Date;
語法上應該要是 `createdAt` 而不是 `createAt`

2023-06-06 13:32 UTC, moontai0724 commented on src/users/exceptions/create-user-badrequest-error.exception.ts
> +            "password 必須長度大於等於8個字。  \n",
hmmm 兩格空格是必要的嗎？

2023-06-06 13:32 UTC, moontai0724 commented on src/users/exceptions/create-user-conflict-error.exception.ts
> +          description: "account 已被註冊。 \n",
hmmm 兩格空格是必要的嗎？

2023-06-06 13:33 UTC, moontai0724 commented on src/users/exceptions/create-user-conflict-error.exception.ts
> +        },
`name` 怎麼會有 conflict？！

2023-06-06 13:37 UTC, moontai0724 commented on src/users/users.module.ts
> +export class UsersModule {}
會建議使用單數 User 而非 Users

2023-06-06 13:37 UTC, moontai0724 commented on src/users/users.module.ts
> +export class UsersModule {}
會建議使用單數 User 而非 Users

2023-06-06 13:37 UTC, moontai0724 commented on src/users/users.service.spec.ts
> +  let service: UsersService;
會建議使用單數 User 而非 Users

2023-06-06 13:37 UTC, moontai0724 commented on src/users/users.service.ts
> +export class UsersService {
會建議使用單數 User 而非 Users

2023-06-06 13:39 UTC, moontai0724 commented on src/users/users.service.spec.ts
> +  });
缺少 service 中 create 方法的測試

2023-06-06 13:43 UTC, moontai0724 commented on src/users/users.service.ts
> +    const hash = await bcrypt.hash(userDto.password, salt);
如果沒有特別在 salt 上設定參數，可以不用特別 genSalt 用 hash/hashSync: `bcrypt.hashSync(userDto.password, times: number)` 就可以了。

2023-06-06 13:44 UTC, moontai0724 requested changes
Comments above.

2023-06-06 15:20 UTC, a20688392 commented on src/auth/auth.service.spec.ts
> +    });
了解030~在次 commit 修正了owo
[af03407](https://github.com/Cophr/backend/pull/7/commits/af034077a7c3ca52b7c82d93e24ed6e30ffce437)

2023-06-06 15:20 UTC, a20688392 commented on src/auth/auth.service.spec.ts
> +    });
了解030~在次 commit 修正了owo
[af03407](https://github.com/Cophr/backend/pull/7/commits/af034077a7c3ca52b7c82d93e24ed6e30ffce437)

2023-06-06 15:20 UTC, a20688392 commented on src/auth/auth.service.spec.ts
> +    });
了解030~在次 commit 修正了owo
[af03407](https://github.com/Cophr/backend/pull/7/commits/af034077a7c3ca52b7c82d93e24ed6e30ffce437)

2023-06-06 15:20 UTC, a20688392 commented on src/auth/auth.service.spec.ts
> +    });
了解030~在次 commit 修正了owo
[af03407](https://github.com/Cophr/backend/pull/7/commits/af034077a7c3ca52b7c82d93e24ed6e30ffce437)

2023-06-06 15:20 UTC, a20688392 commented on src/auth/auth.controller.spec.ts
> +    });
了解030~在次 commit 修正了owo
[af03407](https://github.com/Cophr/backend/pull/7/commits/af034077a7c3ca52b7c82d93e24ed6e30ffce437)

2023-06-06 15:20 UTC, a20688392 commented on src/auth/auth.controller.spec.ts
> +    });
了解030~在此 commit 修正了owo
[af03407](https://github.com/Cophr/backend/pull/7/commits/af034077a7c3ca52b7c82d93e24ed6e30ffce437)

2023-06-06 15:20 UTC, a20688392 commented on src/auth/auth.controller.spec.ts
> +    });
了解030~在次 commit 修正了owo
[af03407](https://github.com/Cophr/backend/pull/7/commits/af034077a7c3ca52b7c82d93e24ed6e30ffce437)

2023-06-06 15:24 UTC, a20688392 commented on src/auth/auth.service.spec.ts
> +      expect(errors.length).toBe(0);
了解030~在此 commit 修正了owo
[d6efa65](https://github.com/Cophr/backend/pull/7/commits/d6efa65c294a61b3ccde171605e64ca50cf227ff)

2023-06-06 15:27 UTC, a20688392 commented on src/auth/auth.controller.spec.ts
> +    it("應該會發生資料驗證失敗，並返回 406 狀態碼", async () => {
修正修正
[24c0968](https://github.com/Cophr/backend/pull/7/commits/24c0968a92fa3b1d584136bd24143773638ac788)

2023-06-06 15:29 UTC, a20688392 commented on src/auth/auth.service.ts
> +    }
乾被發現了ww其實你不講我以為要在多過濾一次，我再刪掉

2023-06-06 15:29 UTC, a20688392 commented on src/users/dto/create-user.dto.ts
> +    description: "登入用帳號名",
不然我試試 account 和 email 都可以登入的設計

2023-06-06 15:31 UTC, a20688392 commented on src/users/exceptions/create-user-badrequest-error.exception.ts
> +            "password 必須長度大於等於8個字。  \n",
會兩個空格是因為他的語法是必需要的，不然不會換行，我還為此找很久到底為甚麼沒換行qq
只有一行的是習慣性加上了

2023-06-06 15:31 UTC, a20688392 commented on src/users/exceptions/create-user-conflict-error.exception.ts
> +          description: "account 已被註冊。 \n",
會兩個空格是因為他的語法是必需要的，不然不會換行，我還為此找很久到底為甚麼沒換行qq
只有一行的是習慣性加上了

2023-06-06 15:31 UTC, a20688392 commented on src/users/exceptions/create-user-conflict-error.exception.ts
> +        },
阿...失誤失誤

2023-06-06 15:45 UTC, a20688392 commented on src/auth/auth.service.ts
> +    }
ㄟ等等
我突然覺得有也不錯?
可以再這裡埋下當除了這錯誤時，寫Error的錯誤，訊息寫來在哪一個檔案的錯誤
這樣會不會以後好debug?

範例:
```
try {
    ````````~~~`````````
    } catch (error) {
      if (error instanceof ConflictException) {
        throw error;
      } else {
        throw new Error(" error happen on auth.service.ts")
      }
    }
```

2023-06-06 15:51 UTC, a20688392 commented on src/users/entities/user.entity.ts
> +  createAt: Date;
已改改
[a804b1e](https://github.com/Cophr/backend/pull/7/commits/a804b1ec2ffea8fbb42f49f8dc365f0bfd36bfc5)

2023-06-06 15:51 UTC, moontai0724 commented on src/auth/auth.service.ts
> +    }
我是覺得應該沒差，畢竟這樣 throw 出來也只是進 500 而已

2023-06-06 15:52 UTC, moontai0724 commented on src/users/exceptions/create-user-badrequest-error.exception.ts
> +            "password 必須長度大於等於8個字。  \n",
原來～那代表是 markdown？那個 `\n` 也有作用嗎？

2023-06-06 16:07 UTC, a20688392 commented on src/users/exceptions/create-user-conflict-error.exception.ts
> +        },
修正
[7a8ebd3](https://github.com/Cophr/backend/pull/7/commits/7a8ebd3b215026963228582ea4ffd5f2af49ece5)

2023-06-06 19:02 UTC, a20688392 commented on src/users/users.service.spec.ts
> +  });
補上補上
[00509f1](https://github.com/Cophr/backend/pull/7/commits/00509f1583032f154f8e9dd61e70bc4f042905c8)

2023-06-07 06:29 UTC, a20688392 commented on src/auth/auth.service.ts
> +    }
窩好吧也是，我在此 commit 刪除了
[f6eccbe](https://github.com/Cophr/backend/pull/7/commits/f6eccbeaf2dc167b5db69c3ece563f1c6f04b008)

2023-06-07 06:35 UTC, a20688392 commented on src/users/exceptions/create-user-badrequest-error.exception.ts
> +            "password 必須長度大於等於8個字。  \n",
也是必須的

關注一下 email 的欄位
以以上面程式碼的結果
![image](https://github.com/Cophr/backend/assets/77681849/697b7816-5a48-48c5-9982-028b5aa73255)

我把兩格空格刪除
![image](https://github.com/Cophr/backend/assets/77681849/7edff270-e030-4c81-9a67-be70dd9903ea)
![image](https://github.com/Cophr/backend/assets/77681849/d5417f2e-15e7-4ccd-9418-32b0b11496c2)

我把\n刪除
![image](https://github.com/Cophr/backend/assets/77681849/b77007e1-3390-41f7-9545-d5c477eeb6fb)
![image](https://github.com/Cophr/backend/assets/77681849/70a81ff0-3d14-44f3-a717-c8d24c7392eb)

2023-06-07 06:36 UTC, a20688392 commented on src/users/exceptions/create-user-conflict-error.exception.ts
> +          description: "account 已被註冊。 \n",
同上

2023-06-07 07:50 UTC, a20688392 commented on src/users/users.service.ts
> +    const hash = await bcrypt.hash(userDto.password, salt);
OK
[2137260](https://github.com/Cophr/backend/pull/7/commits/2137260690530e447642954b477cb4a2b9e7dfb2)

2023-06-08 14:17 UTC, a20688392 commented on src/users/users.service.spec.ts
> +  let service: UsersService;
OK~
[b9f0972](https://github.com/Cophr/backend/pull/7/commits/b9f0972e97ec22c1e69e3af5ecb5a9913ddd9e41)

2023-06-08 14:17 UTC, a20688392 commented on src/users/users.service.ts
> +export class UsersService {
OK~
[00bf9e6](https://github.com/Cophr/backend/pull/7/commits/00bf9e6cbffcf34a76e432a1e2e63f8686de0615)

2023-06-08 14:31 UTC, a20688392 commented on src/users/users.module.ts
> +export class UsersModule {}
OK~
[b9f0972](https://github.com/Cophr/backend/pull/7/commits/b9f0972e97ec22c1e69e3af5ecb5a9913ddd9e41)

2023-06-08 14:44 UTC, a20688392 commented on src/auth/auth.controller.spec.ts
> +  });
驗證是否會正確驗證傳入的 payload，OK
[f33bcc6](https://github.com/Cophr/backend/pull/7/commits/f33bcc68ea7750b403417ee12f65e2f42154ab71)

2023-06-08 14:45 UTC, a20688392 commented
修復完了

2023-06-08 15:23 UTC, moontai0724 requested changes
Tests should not contain external tests that are not related to test target exposed interfaces

2023-06-08 15:24 UTC, moontai0724 commented on src/auth/auth.controller.spec.ts
> +  });
應該要整合到 驗證 `register` 傳入這些參數是否會回傳正確的錯誤

2023-06-08 15:45 UTC, moontai0724 commented on src/users/exceptions/create-user-badrequest-error.exception.ts
> +            "password 必須長度大於等於8個字。  \n",
哭阿，好吧～～

2023-06-08 16:51 UTC, a20688392 commented on src/auth/auth.controller.spec.ts
> +  });
依據剛剛談話和群聊結論
1. 把 DTO 搬移出去驗證，不用測試回應錯誤代碼，照理都是 400 狀態
[039491a](https://github.com/Cophr/backend/pull/7/commits/039491a6aa25f075b74637573635acd3f7a0c108)

2023-06-10 03:28 UTC, moontai0724 approved these changes

2023-06-10 03:28 UTC, moontai0724 commented on src/pipe/validation-pipe.ts
通常這種裡面有多個同樣東西的會用複數 `pipes` 啦，但這還好就看你自己

2023-06-10 03:28 UTC, moontai0724 commented on src/user/dto/create-user.dto.spec.ts
> +describe("user-DTO 驗證", () => {
不用多這一層的 describe

2023-06-10 03:28 UTC, moontai0724 commented on src/user/dto/create-user.dto.spec.ts
> +      const errors = await validate(Dto);
因為使用情境上是使用 `ValidationPipe` 驗證，所以我會比較推薦透過 `ValidationPipe` 來測試，而不是直接 call class validator 的 validate，但這也還好，就看你怎麼想。

2023-06-10 03:29 UTC, moontai0724 approved these changes
Well done!

2023-06-10 07:38 UTC, moontai0724 commented on src/users/dto/create-user.dto.ts
> +    description: "登入用帳號名",
OK 未來處理

2023-06-10 07:40 UTC, a20688392 commented on src/pipe/validation-pipe.ts
OK
[e572da2](https://github.com/Cophr/backend/pull/7/commits/e572da2d4806a9b22a07459b8749e218a94df7b7)

2023-06-10 07:41 UTC, a20688392 commented on src/user/dto/create-user.dto.spec.ts
> +describe("user-DTO 驗證", () => {
OKOK
[8abcc3b](https://github.com/Cophr/backend/pull/7/commits/8abcc3b81125c132625fb83c07561d935ff16df1)

2023-06-10 07:51 UTC, a20688392 commented on src/user/dto/create-user.dto.spec.ts
> +      const errors = await validate(Dto);
OK
[72289d5](https://github.com/Cophr/backend/pull/7/commits/72289d54ea08d8828c90a4627720f2ca0aad28f0)

2023-06-10 07:53 UTC, moontai0724 approved these changes
Well done!

2023-06-10 07:53 UTC, merged